### ISSUE TITLE
Plugin reports 'Invalid' for working edge templates containing an 'R'

### ISSUE THREAD

**Issue by IARI** [Xstoudi/adonis-intellij#18]
I am not sure, how this error happens - but it seems to occur after a capital R letter within the template.

<img width="559" alt="image" src="https://github.com/Xstoudi/adonis-intellij/assets/1053417/4049b95a-fe2a-4c76-8390-5c293420a421">

**Comment by IARI** [comment]
@Xstoudi 
is this a known issue, can it be reproduced?
Can I do something to support?

**Comment by Xstoudi** [comment]
Hey, didn't had time to look into it.
First, I'll appreciate if you can confirm it happens using v0.3.0 of the extension.
Then, if you feel confident with Java language and lexing/parsing voodoo you can try to contribute. If not, I'll look into it asap.

Anyway, thanks for the report!

**Comment by Xstoudi** [comment]
Ok, that was an error in the lexer (53e48616562ec43db13af5ade750f1cc7ac61a95). You'll be able to update manually through GitHub in a few minutes or through marketplace in 1-2 days.
