### ISSUE TITLE
Parsing issue with @if(...) and @end

### ISSUE THREAD

**Issue by IARI** [Xstoudi/adonis-intellij#22]
A Component containing @if @end will not parse - for example:

```
<div class="logo">
  <div>logo</div>
  @if(brand)
    <div>brand</div>
  @end
</div>

```

<img width="174" alt="image" src="https://github.com/Xstoudi/adonis-intellij/assets/1053417/441a52c7-015a-48be-a1f7-6ed43542113c">

**Comment by Xstoudi** [comment]
Should be fixed in next release
