### ISSUE TITLE
Wrong edge icon size

### ISSUE THREAD

**Issue by kilobyte2007** [Xstoudi/adonis-intellij#24]
In PHPStorm the icon looks missized.
I am using MacOS. I am not familiar with how it works so wasn't able to pinpoint the issue yet.
<img width="357" alt="SCR-20240223-nwgn" src="https://github.com/Xstoudi/adonis-intellij/assets/1911258/caddec32-4894-4a7e-b787-4b45f5f4f704">

**Comment by Xstoudi** [comment]
The closest to a reproduction I could get was zooming a lot until the problem appear. I managed to fix it in 0.5.1 under those conditions in a417e8fb4efe62d350e2824118e2588654685bed, please reopen if it's still happening in the next release.

**Comment by kilobyte2007** [comment]
Thanks a lot!
This was on a retina screen so this might have been an important thing I forgot to mention.
I also see that the plugin is not compatible with the latest version - https://plugins.jetbrains.com/plugin/22932-adonis

Can you please push a release to the IntelliJ repository, or how does it work?

**Comment by prisca-c** [comment]
> Thanks a lot! This was on a retina screen so this might have been an important thing I forgot to mention. I also see that the plugin is not compatible with the latest version - https://plugins.jetbrains.com/plugin/22932-adonis
> 
> Can you please push a release to the IntelliJ repository, or how does it work?

A release that handle newer version issue has been done already before this one and these fixes will be available after jetbrains approval ! 😄  [`f5dbe10`](https://github.com/Xstoudi/adonis-intellij/commit/f5dbe10f082701c3bc2f53c945848239917c84be)
