### ISSUE TITLE
Incompatible version with last WS update

### ISSUE THREAD

**Issue by guillermoplus** [Xstoudi/adonis-intellij#25]
WebStorm says that version 0.4.0 of plugin is incompatible.

WS version:
![image](https://github.com/Xstoudi/adonis-intellij/assets/8637358/d1cf5ad9-372a-40c3-8843-2fc7ab12a4f1)

**Comment by prisca-c** [comment]
Opened a pull request about this issue, feel free to take a look ! #26

**Comment by Xstoudi** [comment]
Version 0.5.0 fixing this is waiting Jetbrains approval, you can expect it to be available next Tuesday, maybe already on Monday if lucky.
