### ISSUE TITLE
Consider migrating the project to Kotlin

### ISSUE THREAD

**Issue by Xstoudi** [Xstoudi/adonis-intellij#29]
I don't like Kotlin a lot so I started the project with Java. However, JetBrains is pushing Kotlin a lot in IntelliJ's API and extending or calling Kotlin APIs in Java leads to crappy Java code.

Learning Kotlin and migrating to it could be useful in the next releases.

**Comment by prisca-c** [comment]
I would be glad to take a look at it if it don't bother you !

**Comment by Xstoudi** [comment]
Yeah no problem go ahead. You may need to get back Kotlin workin on the project, you can get the inspiration here: https://github.com/JetBrains/intellij-platform-plugin-template

**Comment by Xstoudi** [comment]
Hey @prisca-c, how is it going?

**Comment by prisca-c** [comment]
@Xstoudi Hey, i've migrated most of the files in folders except the **Edge** one since i've been busy lately, i need to test more to see if everything is working fine

**Comment by Xstoudi** [comment]
Hola, what's up? Any update? I'd like to release the Kotlin migration and some other fixes during second half of July.

**Comment by prisca-c** [comment]
Hey, i'm having exams so it's kinda tought , but i'm gonna work on it this week end + next week so you'll have time to take a look and release it !

**Comment by Xstoudi** [comment]
Finally merged, thank @prisca-c !
