### ISSUE TITLE
2024.2 compatibility

### ISSUE THREAD

**Issue by gquittet** [Xstoudi/adonis-intellij#33]
Hello everyone 👋

I just updated my IntelliJ to 2024.2 because they released the first patch release.

Adonis plugin is not compatible anymore with the latest IntelliJ 2024.2.x release.

Will the Kotlin migration makes this plugin work again with IntelliJ? https://github.com/Xstoudi/adonis-intellij/issues/29

Thanks a lot for the awesome work you do 🙂

**Comment by Xstoudi** [comment]
Hello, I'm really busy and sadly didn't had time to check on #29.
It's still on my todo list and I'll check it asap.

**Comment by rhnkyr** [comment]
@Xstoudi Kotlin is not urgent but you can at least change your version's necessary file(s)

**Comment by Xstoudi** [comment]
v0.5.2 for IntelliJ Platform v242 will be available in 1-2 business days.
